DROP SEQUENCE MYNUMSEQ;
DROP TABLE MBOARD;

CREATE SEQUENCE MYNUMSEQ NOCACHE;
CREATE TABLE MBOARD(
 MYNO NUMBER PRIMARY KEY,
 MYNAME VARCHAR2(1000) NOT NULL,
 MYTITLE VARCHAR2(2000) NOT NULL,
 MYCONTENT VARCHAR2(4000) NOT NULL,
 MYDATE DATE NOT NULL
	
);
INSERT INTO MBOARD VALUES(MYNUMSEQ.NEXTVAL,'관리자','제목','내용',SYSDATE);
SELECT * FROM MBOARD;