DROP SEQUENCE MNOSEQ;
DROP TABLE BOARDD;

CREATE SEQUENCE MNOSEQ NOCACHE;
CREATE TABLE BOARDD(
 	MYNO NUMBER PRIMARY KEY,
 	MYNAME VARCHAR2(1000) NOT NULL,
 	MYTITLE VARCHAR2(2000) NOT NULL,
 	MYCOTNENT VARCHAR2(4000) NOT NULL,
 	MYDATE DATE NOT NULL
);
INSERT INTO BOARDD VALUES(MNOSEQ.NEXTVAL,'NAME','TITLE','CONTENT',SYSDATE);
SELECT * FROM BOARDD;
