DROP SEQUENCE MYNUMSEQ;
DROP TABLE BOARDTEST;

CREATE SEQUENCE MYNUMSEQ NOCACHE;
CREATE TABLE BOARDTEST(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(1000) NOT NULL,
	MYTITLE VARCHAR2(2000) NOT NULL,
	MYCONTENT VARCHAR2(4000) NOT NULL,
	MYDATE DATE NOT NULL
);

INSERT INTO BOARDTEST VALUES(MYNUMSEQ.NEXTVAL,'NAME','TITLE','CONTENT',SYSDATE);
SELECT * FROM BOARDTEST;